--QR_SYS_VW_Bounce
SELECT
	AccountID,
	OYBAccountID,
	JobID,
	ListID,
	BatchID,
	SubscriberID,
	SubscriberKey,
	EventDate,
	IsUnique,
	Domain,
	BounceCategoryID,
	BounceCategory,
	BounceSubcategoryID,
	BounceSubcategory,
	BounceTypeID,
	BounceType,
	SMTPBounceReason,
	SMTPMessage,
	SMTPCode,
	TriggererSendDefinitionObjectID,
	TriggeredSendCustomerKey
FROM _bounce

--QR_SYS_VW_Sent
SELECT AccountID,
       OYBAccountID,
       JobID,
       ListID,
       BatchID,
       SubscriberID,
       SubscriberKey,
       EventDate,
       DOMAIN,
       /*TriggeredSendDefinitionObjectID,*/
       TriggeredSendCustomerKey
FROM _sent

--QR_SYS_VW_Job
SELECT JobID,
       EmailID,
       AccountID,
       AccountUserID,
       FromName,
       FromEmail,
       SchedTime,
       PickupTime,
       DeliveredTime,
       EventID,
       IsMultipart,
       JobType,
       JobStatus,
       ModifiedBy,
       ModifiedDate,
       EmailName,
       EmailSubject,
       IsWrapped,
       TestEmailAddr,
       Category,
       BccEmail,
       OriginalSchedTime,
       CreatedDate,
       CharacterSet,
       IPAddress,
       SalesForceTotalSubscriberCount,
       SalesForceErrorSubscriberCount,
       SendType,
       DynamicEmailSubject,
       SuppressTracking,
       SendClassificationType,
       SendClassification,
       ResolveLinksWithCurrentData,
       EmailSendDefinition,
       DeduplicateByEmail,
       TriggererSendDefinitionObjectID,
       TriggeredSendCustomerKey
FROM _job